/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardIdRouteRouteImport } from './routes/dashboard/$id/route'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DashboardIdIndexRouteImport } from './routes/dashboard/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIdRouteRoute = DashboardIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdIndexRoute = DashboardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/dashboard/$id/': typeof DashboardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/dashboard/$id': typeof DashboardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/dashboard/$id/': typeof DashboardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/$id'
    | '/dashboard/'
    | '/auth/login/'
    | '/dashboard/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/auth/login' | '/dashboard/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/$id'
    | '/dashboard/'
    | '/auth/login/'
    | '/dashboard/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id/': {
      id: '/dashboard/$id/'
      path: '/'
      fullPath: '/dashboard/$id/'
      preLoaderRoute: typeof DashboardIdIndexRouteImport
      parentRoute: typeof DashboardIdRouteRoute
    }
  }
}

interface DashboardIdRouteRouteChildren {
  DashboardIdIndexRoute: typeof DashboardIdIndexRoute
}

const DashboardIdRouteRouteChildren: DashboardIdRouteRouteChildren = {
  DashboardIdIndexRoute: DashboardIdIndexRoute,
}

const DashboardIdRouteRouteWithChildren =
  DashboardIdRouteRoute._addFileChildren(DashboardIdRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardIdRouteRoute: typeof DashboardIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIdRouteRoute: DashboardIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
